<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ $reportTitle }} — {{ $settings['company_name'] ?? 'Quick Prints' }}</title>
@include('pdf._base')
@php
  use App\Support\DocTemplateEngine;
  $accent    = $settings['brand_color'] ?? '#b91c1c';
  $symbol    = $settings['currency_symbol'] ?? 'KSh';
  $logoSrc   = !empty($settings['logo_url']) ? DocTemplateEngine::logoDataUri($settings['logo_url']) : '';
@endphp
<style>
.doc-company-name { color: {{ $accent }}; }
.doc-divider-accent { border-color: {{ $accent }}; }
.bar-fill { background: {{ $accent }}; }
thead th { background: #f9fafb; }
</style>
</head>
<body>
<div class="doc-wrap">

  {{-- Report Header --}}
  <div class="doc-header">
    <div class="doc-header-left">
      @if($logoSrc)
        <img src="{{ $logoSrc }}" style="height:36px;margin-bottom:6px;display:block;">
      @endif
      <div class="doc-company-name">{{ strtoupper($settings['company_name'] ?? 'QUICK PRINTS') }}</div>
      <div class="doc-company-sub">{{ $settings['company_tagline'] ?? '' }}</div>
    </div>
    <div class="doc-header-right">
      <div class="doc-ref" style="font-size:16px;">{{ strtoupper($reportTitle) }}</div>
      <div class="doc-ref-sub">
        Generated: {{ now()->format('d M Y, H:i') }}<br>
        Period: {{ $periodLabel ?? 'All Time' }}<br>
        @if(!empty($branchLabel))Branch: {{ $branchLabel }}@endif
      </div>
    </div>
  </div>
  <hr class="doc-divider doc-divider-accent">

  {{-- KPI Row --}}
  @if(!empty($kpis))
  <div class="kpi-row">
    @foreach($kpis as $kpi)
    <div class="kpi-cell">
      <div class="kpi-label">{{ $kpi['label'] }}</div>
      <div class="kpi-value" style="{{ isset($kpi['color']) ? 'color:'.$kpi['color'].';' : '' }}">{{ $kpi['value'] }}</div>
      @if(!empty($kpi['sub']))<div class="kpi-sub">{{ $kpi['sub'] }}</div>@endif
    </div>
    @endforeach
  </div>
  @endif

  {{-- Sections --}}
  @foreach($sections as $section)
    <div class="section-title">{{ $section['title'] }}</div>

    @if($section['type'] === 'table')
      <table>
        <thead>
          <tr>
            @foreach($section['columns'] as $col)
              <th @if(!empty($col['right'])) class="text-right" @endif>{{ $col['label'] }}</th>
            @endforeach
          </tr>
        </thead>
        <tbody>
          @forelse($section['rows'] as $row)
            <tr>
              @foreach($section['columns'] as $col)
                <td @if(!empty($col['right'])) class="text-right mono" @endif
                    @if(!empty($col['bold'])) style="font-weight:700;" @endif>
                  {{ $row[$col['key']] ?? '—' }}
                </td>
              @endforeach
            </tr>
          @empty
            <tr><td colspan="{{ count($section['columns']) }}" style="text-align:center;color:#999;">No data</td></tr>
          @endforelse
          @if(!empty($section['totals']))
            <tr style="border-top:2px solid #111;">
              @foreach($section['columns'] as $col)
                <td @if(!empty($col['right'])) class="text-right mono" @endif style="font-weight:700;">
                  {{ $section['totals'][$col['key']] ?? '' }}
                </td>
              @endforeach
            </tr>
          @endif
        </tbody>
      </table>

    @elseif($section['type'] === 'bars')
      @php $maxVal = max(1, collect($section['rows'])->max('value')); @endphp
      @foreach($section['rows'] as $row)
        @php $pct = round($row['value'] / $maxVal * 100); @endphp
        <div class="bar-row">
          <div class="bar-label">{{ $row['label'] }}</div>
          <div class="bar-track">
            <div class="bar-fill" style="width:{{ max(2, $pct) }}%;height:10px;border-radius:4px;"></div>
          </div>
          <div class="bar-count">{{ $row['display'] }}</div>
        </div>
      @endforeach

    @elseif($section['type'] === 'text')
      <p style="font-size:13px;color:#555;line-height:1.7;">{{ $section['content'] }}</p>

    @endif
  @endforeach

  <div class="doc-footer">
    Report generated by {{ $settings['company_name'] ?? 'Quick Prints' }} BMS · {{ now()->format('d M Y, H:i') }}
  </div>
</div>
</body>
</html>
